//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.13 at 12:11:20 AM GMT+02:00 
//


package chatData;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the chatData package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Chat_QNAME = new QName("", "chat");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: chatData
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChatDetail }
     * 
     */
    public ChatDetail createChatDetail() {
        return new ChatDetail();
    }

    /**
     * Create an instance of {@link UserData }
     * 
     */
    public UserData createUserData() {
        return new UserData();
    }

    /**
     * Create an instance of {@link MsgData }
     * 
     */
    public MsgData createMsgData() {
        return new MsgData();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChatDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "chat")
    public JAXBElement<ChatDetail> createChat(ChatDetail value) {
        return new JAXBElement<ChatDetail>(_Chat_QNAME, ChatDetail.class, null, value);
    }

}
