//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.13 at 12:11:20 AM GMT+02:00 
//


package chatData;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for users complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="users">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chatCreatorClient" type="{}userData"/>
 *         &lt;element name="otherClient" type="{}userData" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "users", propOrder = {
    "chatCreatorClient",
    "otherClient"
})
public class Users {

    @XmlElement(required = true)
    protected UserData chatCreatorClient;
    @XmlElement(required = true)
    protected List<UserData> otherClient;

    /**
     * Gets the value of the chatCreatorClient property.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getChatCreatorClient() {
        return chatCreatorClient;
    }

    /**
     * Sets the value of the chatCreatorClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setChatCreatorClient(UserData value) {
        this.chatCreatorClient = value;
    }

    /**
     * Gets the value of the otherClient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherClient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherClient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserData }
     * 
     * 
     */
    public List<UserData> getOtherClient() {
        if (otherClient == null) {
            otherClient = new ArrayList<UserData>();
        }
        return this.otherClient;
    }

}
